name: VoidRpGameSync
version: ${version}
main: ru.voidrp.gamesync.VoidRpGameSyncPlugin
api-version: '1.21'
authors: [VoidRP]
softdepend: [Vault, LuckPerms, PlaceholderAPI, WorldGuard]
commands:
  vrgs:
    description: VoidRP game sync admin command
    usage: /vrgs
    permission: voidrp.gamesync.admin
permissions:
  voidrp.gamesync.admin:
    default: op
